import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { CartService } from '../../shared/services/cart.service';

interface ProductDetail { id:number; name:string; category:string; price:number; image:string; originalPrice?:number; stock:string; stockCount:number; badge?:string; rating:number; reviews:number; description:string; longDescription:string; dimensions:{label:string;value:string}[]; materials:string[]; finishes:string[]; colours:{name:string;hex:string}[]; care:string[]; images:string[]; sku:string; }

@Component({ selector:'app-product-details', standalone:true, imports:[CommonModule, RouterLink], templateUrl:'./product-details.component.html', styleUrl:'./product-details.component.scss' })
export class ProductDetailsComponent implements OnInit {
  activeImage = ''; activeImageIndex = 0; quantity = 1; activeTab = 'description'; selectedFinish = ''; selectedColour = ''; zoomActive = false; zoomStyle: Record<string,string> = {}; addedToCart = false; cartToast = false; cartToastMsg = '';
  product: ProductDetail = { id:4, name:'Luna Lounge Chair', category:'Lounge Chairs', price:85000, image:'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=85', originalPrice:95000, stock:'In Stock', stockCount:4, badge:'Bestseller', rating:5, reviews:31, sku:'SYM-LC-001', description:'A sculptural lounge chair that brings refined comfort and quiet presence to an interior.', longDescription:'The Luna Lounge Chair pairs an organically shaped solid walnut frame with hand-finished leather upholstery. Its deep seat and gentle recline are designed for slow mornings, reading and conversation.\n\nEach piece is handcrafted to order in Hyderabad. Custom dimensions, leather grades and frame finishes are available on request.', dimensions:[{label:'Width',value:'82 cm'},{label:'Depth',value:'88 cm'},{label:'Height',value:'76 cm'},{label:'Seat Height',value:'42 cm'}], materials:['Frame: Solid FSC-certified American Walnut','Upholstery: Full-grain Italian leather','Filling: High-density HR foam with Dacron wrap'], finishes:['Natural Walnut','Smoked Oak','Ebonised Walnut','Painted White'], colours:[{name:'Cognac',hex:'#8B4513'},{name:'Ivory',hex:'#FFFFF0'},{name:'Slate',hex:'#708090'},{name:'Forest',hex:'#355E3B'}], care:['Dust regularly with a soft, dry cloth','Clean spills immediately with a slightly damp cloth','Avoid direct sunlight and harsh chemical cleaners'], images:['https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=900&q=85','https://images.unsplash.com/photo-1567016432779-094069958ea5?w=900&q=85','https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=900&q=85'], };
  relatedProducts = [{id:5,name:'Noir Accent Chair',category:'Lounge Chairs',price:92000,image:'https://images.unsplash.com/photo-1567016432779-094069958ea5?w=500&q=80'},{id:6,name:'Arca Reading Chair',category:'Lounge Chairs',price:110000,image:'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=500&q=80'},{id:1,name:'Linea Sofa',category:'Luxury Sofas',price:195000,image:'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=500&q=80'},{id:10,name:'Forma Coffee Table',category:'Coffee Tables',price:65000,image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500&q=80'}];
  constructor(private route: ActivatedRoute, private router: Router, private cart: CartService) {}
  ngOnInit() { this.activeImage = this.product.images[0]; this.selectedFinish = this.product.finishes[0]; this.selectedColour = this.product.colours[0].name; }
  setImage(image:string, index:number) { this.activeImage = image; this.activeImageIndex = index; }
  prevImage() { const i = (this.activeImageIndex - 1 + this.product.images.length) % this.product.images.length; this.setImage(this.product.images[i],i); }
  nextImage() { const i = (this.activeImageIndex + 1) % this.product.images.length; this.setImage(this.product.images[i],i); }
  onMouseMove(event:MouseEvent) { const rect = (event.currentTarget as HTMLElement).getBoundingClientRect(); this.zoomStyle = {'transform-origin': `${((event.clientX-rect.left)/rect.width)*100}% ${((event.clientY-rect.top)/rect.height)*100}%`, transform:'scale(2.2)'}; }
  addToCart() { this.cart.add(this.product, this.quantity); this.addedToCart = true; this.cartToast = true; this.cartToastMsg = `${this.quantity} × ${this.product.name} added to cart`; setTimeout(() => { this.addedToCart = false; this.cartToast = false; }, 2200); }
  buyNow() { this.cart.add(this.product, this.quantity); this.router.navigate(['/checkout']); }
  stars(n:number) { return Array(n).fill(0); }
}
